//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sportivex.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sportivex.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4KAAD_Eyewear_pink_ {
            get {
                object obj = ResourceManager.GetObject("4KAAD Eyewear(pink)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _61TKGyNGNAL__AC_SL1500_ {
            get {
                object obj = ResourceManager.GetObject("61TKGyNGNAL._AC_SL1500_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _71A0AxD2z3L__AC_SL1500_ {
            get {
                object obj = ResourceManager.GetObject("71A0AxD2z3L._AC_SL1500_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _71A0AxD2z3L1 {
            get {
                object obj = ResourceManager.GetObject("71A0AxD2z3L1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Aluminum_Portable_Bike_Floor_Tire_Pump {
            get {
                object obj = ResourceManager.GetObject("Aluminum Portable Bike Floor Tire Pump", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Best_Bike_Pump_640x448 {
            get {
                object obj = ResourceManager.GetObject("Best-Bike-Pump-640x448", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Bicycle_Pump {
            get {
                object obj = ResourceManager.GetObject("Bicycle Pump", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BIKE_PUMP_aluminum_alloy_Mini_Portable_Bike_pump {
            get {
                object obj = ResourceManager.GetObject("BIKE PUMP aluminum alloy Mini Portable Bike pump", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exustar_bike_parts_accessories_e_pr2blk_64_1000 {
            get {
                object obj = ResourceManager.GetObject("exustar-bike-parts-accessories-e-pr2blk-64_1000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exustar_bike_parts_accessories_e_pr2blk_64_10001 {
            get {
                object obj = ResourceManager.GetObject("exustar-bike-parts-accessories-e-pr2blk-64_10001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Favoto_Helmet {
            get {
                object obj = ResourceManager.GetObject("Favoto Helmet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap foamgrip {
            get {
                object obj = ResourceManager.GetObject("foamgrip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Group_1 {
            get {
                object obj = ResourceManager.GetObject("Group 1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HEURE_Eyewear {
            get {
                object obj = ResourceManager.GetObject("HEURE Eyewear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Kapvoe_Eyewear {
            get {
                object obj = ResourceManager.GetObject("Kapvoe Eyewear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Kask_Helmet_Blue_ {
            get {
                object obj = ResourceManager.GetObject("Kask Helmet(Blue)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kaskprotonhelmet {
            get {
                object obj = ResourceManager.GetObject("kaskprotonhelmet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kaskprotonhelmet1 {
            get {
                object obj = ResourceManager.GetObject("kaskprotonhelmet1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kaskprotonhelmet2 {
            get {
                object obj = ResourceManager.GetObject("kaskprotonhelmet2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap KOO_Eyewear__Green_ {
            get {
                object obj = ResourceManager.GetObject("KOO Eyewear (Green)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lockon_grip {
            get {
                object obj = ResourceManager.GetObject("lockon grip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lockon_grip1 {
            get {
                object obj = ResourceManager.GetObject("lockon grip1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mountainbike_pedal {
            get {
                object obj = ResourceManager.GetObject("mountainbike pedal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OnGuard_Bulldog_DT_Bike_Lock_U_Lock_and_Cable_Combo3 {
            get {
                object obj = ResourceManager.GetObject("OnGuard Bulldog DT Bike Lock U-Lock and Cable Combo3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OnGuard_Bulldog_DT_Bike_Lock_U_Lock_and_Cable_Combo31 {
            get {
                object obj = ResourceManager.GetObject("OnGuard Bulldog DT Bike Lock U-Lock and Cable Combo31", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OnGuard_Bulldog_DT_Bike_Lock_U_Lock_and_Cable_Combo32 {
            get {
                object obj = ResourceManager.GetObject("OnGuard Bulldog DT Bike Lock U-Lock and Cable Combo32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OnGuard_Doberman_Coil_Cable_Bike_Lock1 {
            get {
                object obj = ResourceManager.GetObject("OnGuard Doberman Coil Cable Bike Lock1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OnGuard_Doberman_Coil_Cable_Bike_Lock11 {
            get {
                object obj = ResourceManager.GetObject("OnGuard Doberman Coil Cable Bike Lock11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OnGuard_Doberman_Coil_Cable_Bike_Lock2 {
            get {
                object obj = ResourceManager.GetObject("OnGuard Doberman Coil Cable Bike Lock2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OnGuard_Mastiff_Bike_Lock___Chain_Lock6 {
            get {
                object obj = ResourceManager.GetObject("OnGuard Mastiff Bike Lock - Chain Lock6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OnGuard_Pitbull_STD_Bike_Lock_U_Lock4 {
            get {
                object obj = ResourceManager.GetObject("OnGuard Pitbull STD Bike Lock U-Lock4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OnGuard_Rottweiler_Bike_Lock_8024___Armored_Lock5 {
            get {
                object obj = ResourceManager.GetObject("OnGuard Rottweiler Bike Lock 8024 - Armored Lock5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OnGuard_Rottweiler_Bike_Lock_8024___Armored_Lock51 {
            get {
                object obj = ResourceManager.GetObject("OnGuard Rottweiler Bike Lock 8024 - Armored Lock51", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OnGuard_Rottweiler_Bike_Lock_8024___Armored_Lock52 {
            get {
                object obj = ResourceManager.GetObject("OnGuard Rottweiler Bike Lock 8024 - Armored Lock52", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OnGuard_Rottweiler_Bike_Lock_8024___Armored_Lock53 {
            get {
                object obj = ResourceManager.GetObject("OnGuard Rottweiler Bike Lock 8024 - Armored Lock53", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pedals_mtb_scm204_front {
            get {
                object obj = ResourceManager.GetObject("pedals-mtb-scm204-front", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rnoxhelmet {
            get {
                object obj = ResourceManager.GetObject("rnoxhelmet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rnoxhelmet1 {
            get {
                object obj = ResourceManager.GetObject("rnoxhelmet1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rnoxhelmet2 {
            get {
                object obj = ResourceManager.GetObject("rnoxhelmet2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rubbergrip {
            get {
                object obj = ResourceManager.GetObject("rubbergrip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SCVCN_Eyewear {
            get {
                object obj = ResourceManager.GetObject("SCVCN Eyewear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Shimano_Eyewear {
            get {
                object obj = ResourceManager.GetObject("Shimano Eyewear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Shimano_RS500_SPD_SL_Pedal {
            get {
                object obj = ResourceManager.GetObject("Shimano-RS500-SPD-SL-Pedal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Shimano_RS500_SPD_SL_Pedal1 {
            get {
                object obj = ResourceManager.GetObject("Shimano-RS500-SPD-SL-Pedal1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sportivex_removebg_preview__2_ {
            get {
                object obj = ResourceManager.GetObject("sportivex-removebg-preview (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap The_MEETLOCKS_Bike_Pedal_Injection_Magnesium_Alloy_Body_Cr_Mo_Machined_9_16_inch_Screw_Thread_Spindle_Ultra_DU_Sealed_Bearings {
            get {
                object obj = ResourceManager.GetObject("The-MEETLOCKS-Bike-Pedal-Injection-Magnesium-Alloy-Body-Cr-Mo-Machined-9-16-inch-" +
                        "Screw-Thread-Spindle-Ultra-DU-Sealed-Bearings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Van_Rysel_Helmet {
            get {
                object obj = ResourceManager.GetObject("Van Rysel Helmet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap VictGoal_Helmet_RED_ {
            get {
                object obj = ResourceManager.GetObject("VictGoal Helmet(RED)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap VictGoal_Helmet_RED_1 {
            get {
                object obj = ResourceManager.GetObject("VictGoal Helmet(RED)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
